# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [7]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [2]:
cars1 = pd.read_csv('cars1.csv')
cars2 = pd.read_csv('cars2.csv')

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [ ]:
cars1 = cars1.dropna(axis=1, how='all')
cars1
# .dropna check and remove all the columns/rows that does not contain any data, axis=1 to delete columns, how='all' to delete if there is absolute no data
# distinguish with sum of dataframe which sum by column by default

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [4]:
print(f"Num 1: {cars1.shape[0]}")
print(f"Num 2: {cars2.shape[0]}")

Num 1: 198
Num 2: 200

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [ ]:
cars = pd.concat([cars1, cars2])
cars
# pd.concat receive a list of entities that need to concatenate

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [ ]:
series = np.random.randint(15000, 73000, cars.shape[0])
print(series)
# param: start, end, size

[28150 31699 21822 64112 41426 50749 44365 45853 16808 55625 29484 68856
 26575 47596 54193 41402 16347 18521 61689 66555 42167 40134 15410 58858
 56241 60430 21976 42442 66515 61011 47077 30986 43178 16943 57158 62418
 33293 70758 66931 26475 33049 67296 15227 67150 49911 42049 50942 27507
 53867 68337 53300 15661 28053 65010 24586 44271 42338 43046 41391 30476
 45723 65275 53058 59074 32107 35834 69454 17891 30109 72003 30583 28046
 39112 62540 70440 24115 21204 70672 16780 71035 39667 66827 25261 66749
 28341 37642 58081 72336 19366 38429 22136 63179 29463 60576 19261 42529
 68880 28888 53173 36286 70574 42705 61781 47958 44981 64255 58022 28493
 39856 56260 53346 57279 47396 29923 59947 42729 45999 27923 17798 46597
 67645 58231 20161 68197 17786 53028 18267 61282 28201 61637 56069 17065
 52149 54306 26889 68285 39674 43036 28600 40851 46950 39570 15715 66785
 47102 60443 28421 43103 21785 68814 16651 24718 52851 17370 61049 66939
 23744 18782 32778 72381 19652 62527 57309 31378 33184 29093 66437 24176
 61476 45966 36231 18190 33261 25383 21301 72258 25553 39873 16413 46336
 40024 28757 63972 33538 36340 47374 15036 24452 52577 58170 43166 36532
 33957 37293 34456 72799 35218 49060 16992 23717 61434 49884 46707 47848
 46286 62367 44542 72905 49674 37745 33718 21501 22382 62741 34334 35920
 64628 27770 25295 33584 72779 43933 17957 21200 28281 30833 27624 46001
 72931 64006 19679 19651 24915 34432 65326 15130 44295 61395 58966 53620
 56673 51392 56146 51427 71994 48651 18543 57598 37947 57270 53678 25164
 21283 33802 61055 62596 20412 27463 37957 43325 48072 60755 33449 49317
 37339 29778 20664 23870 26900 17492 15725 61141 41321 66477 40310 50519
 44788 43484 44597 51393 52981 19971 18944 39160 61998 70219 21706 70375
 57694 54544 39349 44089 21608 61771 34071 64642 58022 22998 44667 51390
 30139 26100 26785 51322 36461 48580 20470 34540 66405 38056 58433 58360
 30634 20376 49253 21610 56219 64286 69973 22463 72383 36624 18455 16742
 28137 16727 46837 60007 31927 71915 65861 22227 21552 67359 20084 28933
 28006 54684 51212 38306 36780 19060 69665 66604 51849 52886 44344 72589
 56563 70116 70685 56436 49109 63216 51217 57777 33814 58361 37519 27562
 32407 35605 66473 26732 31324 66779 28291 41270 42124 47096 53714 59751
 50469 59814 50203 47779 23556 60477 54283 40239 66855 41116 33259 54283
 41312 39154 68217 64080 34087 31051 49486 71946 48770 70525 20242 24534
 17537 43542]

### Step 8. Add the column owners to cars

In [8]:
cars['owners'] = np.random.randint(15000, 73000, cars.shape[0])
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,65329
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,66242
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,15863
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,15768
4,17.0,8,302,140,3449,10.5,70,1,ford torino,54606
...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,44354
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,66552
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,61953
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,19323
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,42604